[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "unitofworkfunction"
description = "Function that demonstrates UnitOfWork API."
type = "function"
salesforce-api-version = "55.0"
access="public"
